### ISSUE TITLE
横歩取りのタグの判定

### ISSUE THREAD

**Issue by mizar** [mizar/sylwi-kifu-vue#3]
関連: https://github.com/mizar/shogi-castle-js/issues/1

## 指摘

https://twitter.com/DenryuSen/status/1290612659616755712
> 実験 7回戦☗Sylwi予行電竜-☖dummy9 17手目 ☗３四飛
>
> 横歩…なのか…？
> https://golan.sakura.ne.jp/denryusen/dr1_test3/dist/denryusen.php?gi=dr1t3t1+tv-7_sylwi_dummy9-300-1F+sylwi+dummy9+20200804012618&te=17&mv=%E2%98%97%EF%BC%93%E5%9B%9B%E9%A3%9B&gn=%E5%AE%9F%E9%A8%93%207%E5%9B%9E%E6%88%A6%E2%98%97Sylwi%E4%BA%88%E8%A1%8C%E9%9B%BB%E7%AB%9C-%E2%98%96dummy9 #電竜戦 @DenryuSenより

※ 電竜戦棋譜中継サイトからはファイル消失、棋譜ファイル → [dr1t3t1+tv-7_sylwi_dummy9-300-1F+sylwi+dummy9+20200804012618.csa](https://github.com/mizar/sylwi-kifu-vue/files/5599391/dr1t3t1%2Btv-7_sylwi_dummy9-300-1F%2Bsylwi%2Bdummy9%2B20200804012618.csa.txt)

https://twitter.com/JKishi18gou/status/1290614965406060544
> 銀が動いてなくて、☗７八金、☖３二金が入っている……ぐらい入れておけばいいのかも。

https://twitter.com/bleu48/status/1290613742938419200
> 所謂横歩取り戦法なら15手目ですね。 #手順前後で合流したりするのはどうするのか

## 現状の定義

```yaml
- id: SENTE_SHAPE_YOKOFU
  name:
    ja_JP: 先手横歩
    en_US: SENTE_SHAPE_YOKOFU
  moves:
    - R*2d3d
  capture:
    - p
  tags_disable:
    - SHAPE_AIGAKARI
  tesuu_max: 20
  moves_readable:
    - ☗２四飛→☗３四飛
  capture_readable:
    - ☖歩
```

## 棋譜

> ▲７六歩 △８四歩 ▲７八銀 △３四歩 ▲７七銀 △７二銀 ▲２六歩 △３二金 ▲２五歩 △６四歩 ▲７八金 △７四歩 ▲２四歩 △同　歩 ▲同　飛 △８五歩 ▲３四飛

## 局面(BOD)
```
後手の持駒：歩 
  ９ ８ ７ ６ ５ ４ ３ ２ １
+---------------------------+
|v香v桂 ・v金v玉 ・v銀v桂v香|一
| ・v飛v銀 ・ ・ ・v金v角 ・|二
|v歩 ・ ・ ・v歩v歩 ・ ・v歩|三
| ・ ・v歩v歩 ・ ・ 飛 ・ ・|四
| ・v歩 ・ ・ ・ ・ ・ ・ ・|五
| ・ ・ 歩 ・ ・ ・ ・ ・ ・|六
| 歩 歩 銀 歩 歩 歩 歩 ・ 歩|七
| ・ 角 金 ・ ・ ・ ・ ・ ・|八
| 香 桂 ・ ・ 玉 金 銀 桂 香|九
+---------------------------+
先手の持駒：歩二 
後手番
手数＝17  ▲３四飛 まで
```
